version: "3.8"

services:
  openvpn:
    image: kylemanna/openvpn
    container_name: openvpn
    environment:
      - OVPN_DEBUG=yes
      - DEBUG=1
    cap_add:
      - NET_ADMIN
    ports:
      - "1194:1194/tcp"
    networks:
      - backend
    volumes:
      - openvpn-data:/etc/openvpn

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    cap_add:
      - NET_ADMIN
    depends_on:
      - openvpn
    networks:
      backend: 
        ipv4_address: 10.0.0.10
    volumes:
      - ./docker/mosquitto.conf:/mosquitto/config/mosquitto.conf
  ntp:
    image: cturra/ntp
    container_name: ntp
    environment:
      - NTP_SERVERS=
    cap_add:
      - NET_ADMIN
    depends_on:
      - openvpn
    networks:
      backend: 
        ipv4_address: 10.0.0.11

networks:
  backend:
    ipam:
      config:
        - subnet: 10.0.0.0/24

volumes:
  openvpn-data:
    external: true
